### ISSUE TITLE
drop-down link cuts into text

### ISSUE THREAD

**Issue by janetpkr** [jkhedani/taaccct#3] opened 2015-01-08 00:27 UTC
This one https://jkhedani.github.io/taaccct/#portfolio. Dunno if that's preventable, but would be nice to see the tops of the letters

**Comment by billymeinke** [comment] 2015-01-09 01:52
done, duplicate of https://github.com/jkhedani/taaccct/issues/8

**Closed as completed by billymeinke** 2015-01-09 01:52 UTC
Labels: duplicate
